import type { Metadata } from "next";
import "./globals.css";
import { EB_Garamond } from "next/font/google";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const ebGaramond = EB_Garamond({ subsets: ['latin'] })


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ebGaramond.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
